config/routes.rb
Rails.application.routes.draw do
  get 'movies/search'
  get 'movies/show'

  devise_for :users

  root "users#index"
  resources :users do
    member do
      get :following, :followers, :users_tweets
    end
  end
  resources :messages, only: [:index]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
  end
  resources :posts
  resources :my_rankings do
    put :sort
  end
  resources :relationships
  resources :movies, only: [:show, :search]
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :content, presence: true, unless: :image?
  
  mount_uploader :image, ImageUploader
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      redirect_to group_messages_path(@group), notice: 'メッセージが送信されました'
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/views/messages/_main_chat.html.haml
.message_main
  .message_main-header
    .message_main-header__box
      .main-header__box__leftbox
        .message_main-header__box__leftbox--group_name
          = @group.name
        .message_main-header__box__leftbox--user_name
          - @group.users.each do |user|
            =user.name
      =link_to edit_group_path(@group.id) do
        .message_main-header__box__edit-btn
          edit
  .messages
    .message
      = render @messages

  .message_form
    = form_for [@group, @message] do |f|
      .message_form__box
        .message_form__box__message-area
          = f.text_field :content, class: 'message_form__box__message-area--text', placeholder: 'type a message'
          .message_form__mask
            = f.label :image, class: 'message_form__box__message-area__pic' do
              = icon('fas', 'image')
              = f.file_field :image, class: 'message_form__box__message-area__pic--icon'
        = f.submit 'Send', class: 'message_form__box__send-btn'

app/views/messages/_message.html.haml
.message{data: {message: {id: message.id}}}
  .message__info
    %p.message__info--name
      = message.user.name
    %p.message__info--date
      = message.created_at.strftime("%Y年%m月%d日 %H時%M分")
  - if message.content.present?
    %p.message__content
      = message.content
  = image_tag message.image.url, class: 'lower-message__image' if message.image.present?

app/views/messages/_side_bar.html.haml
.side
  .side-header
    .side-header__box
      .side-header__box--name
        = current_user.name
      .side-header__box__btn
        = link_to new_group_path do
          = icon('far', 'edit', class: 'side-header__box__btn--edit')
        = link_to edit_user_path(current_user) do
          = icon('fas', 'cog', class: 'side-header__box__btn--cog')
  .groups
    - current_user.groups.each do |group|
      .groups__group
        = link_to group_messages_path(group) do
          %p.groups__group--name
            = group.name
          %p.groups__group--message
            = group.show_last_message

app/views/messages/index.html.haml
.wrapper
  = render "main_chat"