config/routes.rb
Rails.application.routes.draw do
  get 'movies/search'
  get 'movies/show'

  devise_for :users

  root "users#index"
  resources :users do
    member do
      get :following, :followers, :users_tweets
    end
  end
  resources :messages, only: [:index]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
  end
  resources :posts
  resources :my_rankings do
    put :sort
  end
  resources :relationships
  resources :movies, only: [:show, :search]
end

app/models/my_ranking.rb
class MyRanking < ApplicationRecord
  include RankedModel
  ranks :row_order

  belongs_to :user
end

app/controllers/my_rankings_controller.rb
class MyRankingsController < ApplicationController
  def index
    @myRanking = MyRanking.where(user_id: current_user.id).rank(:row_order)
  end

  def new
    @myRanking = MyRanking.new
  end

  def create
    MyRanking.create(my_ranking_params)
    redirect_to my_rankings_path
  end

  def edit
    @MyRanking = MyRanking.find(params[:id])
  end

  def update
    myRanking = MyRanking.find(params[:id])
    myRanking.update(my_ranking_params)
    redirect_to my_rankings_path
  end

  def show
    @MyRanking = MyRanking.find(params[:id])
  end

  def destroy
    myRanking = MyRanking.find(params[:id])
    myRanking.destroy
    redirect_to my_rankings_path
  end

  def sort
    myRanking = MyRanking.find(params[:my_ranking_id])
    myRanking.update(my_ranking_params)
    render nothing: true
  end

  private
  def my_ranking_params
    params.require(:my_ranking).permit(:title, :content, :row_order_position).merge(user_id: current_user.id)
  end

end

app/views/my_rankings/edit.html.haml
.content__title
  投稿の編集

.form
  = form_for [@MyRanking] do |f|
    = f.text_field :title, class: 'form__title', placeholder: 'タイトル'
    = f.text_area :content, class: 'form__text', placeholder: 'ブログ本文'
    = f.submit '投稿する', class: 'form__btn'

app/views/my_rankings/index.html.haml
%p#notice= notice
%h1 MyMovieRanking
%table.table
  %thead
    %tr
      %th 
        タイトル
      %th 
        感想
      %th 
        表示
      %th 
        編集
      %th 
        削除
  %tbody.table-sortable
    - @myRanking.each do |myrank|
      %tr.item{"data-model-name": myrank.class.name.underscore, "data-update-url": my_ranking_sort_path(myrank)}
        %td
          = myrank.title
        %td
          = myrank.content
        %td
          = link_to 'Show', myrank
        %td
          = link_to 'Edit', edit_my_ranking_path(myrank)
        %td
          = link_to 'Destroy', myrank, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to '新規登録', new_my_ranking_path

app/views/my_rankings/new.html.haml
.content__title
  新規登録

.form
  = form_for [@myRanking] do |f|
    = f.text_field :title, class: 'form__title', placeholder: '映画タイトル'
    = f.text_area :content, class: 'form__text', placeholder: '感想'
    = f.submit '投稿する', class: 'form__btn'

app/views/my_rankings/show.html.haml
.postTitle
  = @MyRanking.title
.postDate
  = @MyRanking.created_at
.postAuthor
.postManage
  -# - if user_signed_in? && current_user.id == @post.user_id
  -#   =link_to edit_post_path(@MyRanking.id), class: "postManage__edit" do
  -#     編集
  -#   = link_to post_path(@MyRanking.id), method: :delete, class: "postManage__delete" do
  -#     削除
.postText
  = simple_format @MyRanking.content 