config/routes.rb
Rails.application.routes.draw do
  get 'movies/search'
  get 'movies/show'

  devise_for :users

  root "users#index"
  resources :users do
    member do
      get :following, :followers, :users_tweets
    end
  end
  resources :messages, only: [:index]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
  end
  resources :posts
  resources :my_rankings do
    put :sort
  end
  resources :relationships
  resources :movies, only: [:show, :search]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  # validates :name, presence: true, uniqueness: true
  has_many :group_users
  has_many :groups, through: :group_users
  has_many :messages
  has_many :posts
  has_many :MyRankings

  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships

  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end
  mount_uploader :profile_img, ImageUploader
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @search_term = params[:looking_for]
    movie = @search_term ? Movie.search(@search_term) : Movie.index
    @movie_results = movie["results"]
    # 自分以外のユーザーを取得。全ユーザー取得なら User.all
    @users = User.where.not(id: current_user.id)
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def following
    @title = "フォロー"
    @user = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
  end

  def followers
    @title = "フォロワー"
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_follow'
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :introduction, :profile_img)
  end
end

app/views/users/_follow.html.haml
= form_for(current_user.following_relationships.build(following_id: user.id),remote: true) do |f|
  %div
    = f.hidden_field :following_id
    = f.submit "Follow", class: "btn btn-large btn-primary"

app/views/users/_follow_form.html.haml
- unless current_user.id == user.id
  #follow_form
    - if current_user.following?(user)
      = render 'unfollow', user: user
    - else
      = render 'follow', user: user

app/views/users/_stats.html.haml
- @user ||= current_user
.stats
  %a{:href => "#{following_user_path(@user)}"}
    %strong#following.stat
      = @user.followings.count
    フォロー
   
  %a{:href => "#{followers_user_path(@user)}"}
    %strong#followers.stat
      = @user.followers.count
    フォロワー

app/views/users/_unfollow.html.haml
= form_for(current_user.following_relationships.find_by(following_id: user.id),html: { method: :delete },remote: true) do |f|
  = f.submit "Unfollow", class: "btn btn-large btn-danger"


= form_for(current_user, url: relationship_path(@user), method: :delete, remote: true) do |f|
  = f.submit "フォロー解除", class: "btn btn-outline-secondary"

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      %br
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "マイページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      %img(src="#{current_user.profile_img}" alt  onerror="this.onerror = null; this.src='';")
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .field
          .field-label
            = f.label :introduction
          .field-input
            = f.text_area :introduction ,class: "text-area-size"
        .field
          .field-label
            = f.label :profile_img
          .field-input
            = f.file_field :profile_img
        .actions
          = f.submit "Update", class: 'btn'

app/views/users/index.html.haml
%h1 
  上映中の映画情報
.main_content
  .row
    .col-xs-12
      - @movie_results.each do |movie|
        .col-xs-3
          = link_to movie_path(movie["id"]) do
            %img(src= "https://image.tmdb.org/t/p/w200#{movie["poster_path"]}" alt= "poster")
            %br
            = movie["title"]
          -# = link_to movie["title"], controller = '%br' ,action: 'show', id: "#{movie["id"]}"
          %br
          = "リリース日：#{movie["release_date"]}"
  %hr.accessory
  %h2 ユーザー情報
  .user_fiield
    .row
      .col-xs-12
        - @users.each do |user|
          .col-xs-3
            = link_to "/users/#{user.id}" do
              %img(src="#{user.profile_img}" alt class="img-thumbnail"  onerror="this.onerror = null; this.src='';")
            %br
              = "名前：#{user.name}"
            .my_content__movie_ranking{ id: "movie_ranking" }
              .ranking_area
                My Movie Ranking
                - MyRanking.select{|mr| mr.user_id == user.id}.each.with_index(1) do |myrank|
                  = myrank.title

app/views/users/show.html.haml
.my_profile
  .my_content
    %p
      %img
    .my_content__profile{ id: "profile" }
      %header
        %h1
          プロフィール
          %span
      %img(src="#{@user.profile_img}" alt  onerror="this.onerror = null; this.src='';" class="img-thumbnail")
      %p #{@user.name}
      .my_content__profile--introduction
        = @user.introduction
      - if @user.id == current_user.id 
        = link_to edit_user_path(current_user) do
          プロフィールを編集する
          = icon('fas', 'cog', class: 'icon')

    .my_content__friends{ id: "friend" }
      %span.follow-wrapper{:id => "user_#{@user.id}"}
        = render 'follow_form', user: @user if signed_in?
        %h4
        = render 'users/stats'

    .my_content__movie_ranking{ id: "movie_ranking" }
      %h2.user_content
        マイムービーランキング
      - if @user.id == current_user.id 
        .btn_area
          = link_to my_rankings_path , class: "btn btn-primary" , data: {"turbolinks" => false} do
            マイムービーランキングを設定する
      .ranking_area
        %ul
          - @user.MyRankings.each.with_index(1) do |myrank, i|
            %li
              .rank
                = link_to myrank, class: "new_btn" do
                  #{i}位 #{myrank.title} 


    .my_content__review{ id: "review" }
      %h2.user_content
        レビュー
      .btn_area
        = link_to posts_path(user: @user.id), class: "btn btn-primary" do
          すべてのレビューを見る
        - if @user.id == current_user.id 
          -# .new-review-btn
          = link_to movies_search_path, class: "btn btn-primary new-review-btn" do
            レビューする
      %ul
        - @posts.last(5).each do |post|
          %li
            .li_content
              = link_to  post_path(post.id), class: "content__right__top--title" do
                %img(src= "https://image.tmdb.org/t/p/w200/#{post.poster_path}" alt= "poster")
                %p
                %div{id: "star-rate-#{post.id}"}
                %p
                = post.title
                :javascript
                  $('#star-rate-#{post.id}').raty({
                    size: 36,
                    starOff:  '#{asset_path('star-off.png')}',
                    starOn : '#{asset_path('star-on.png')}',
                    starHalf: '#{asset_path('star-half.png')}',
                    half: true,
                    readOnly: true,
                    score: #{post.rate},
                  });
    - if @user.id == current_user.id 
      .my_content__message{ id: "message" }
        %h2.user_content
          メッセージ
        .btn_area
          = link_to new_group_path ,class: "btn btn-primary" do
            メッセージグループを作成する
            = icon('far', 'edit', class: 'side-header__box__btn--edit')
        %ul
          - @user.groups.each do |group|
            %li
              .li_content.card
                .card-body
                  グループ名：
                  = link_to group_messages_path(group) do
                    = group.name
                  %p.card-text
                    最終メッセージ：
                    = group.show_last_message
                  %p.card-text
                    メンバー
                  - group.users.each do |user|
                    %img(src="#{user.profile_img}" alt class="img-thumbnail" onerror="this.onerror = null; this.src='';")

app/views/users/show_follow.html.haml
.container
  .row
    %aside.span4
      %section
        = render 'users/stats'
        %h2= @title
      .user_fiield
        - if @users.any?
          - @users.each do |user|
            .user_avatars
              %span
                %img(src = "#{user.profile_img}" class="img-thumbnail" width="200")
              %br/
              = link_to user.name ,user_path(user)