config/routes.rb
Rails.application.routes.draw do
  get 'movies/search'
  get 'movies/show'

  devise_for :users

  root "users#index"
  resources :users do
    member do
      get :following, :followers, :users_tweets
    end
  end
  resources :messages, only: [:index]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
  end
  resources :posts
  resources :my_rankings do
    put :sort
  end
  resources :relationships
  resources :movies, only: [:show, :search]
end

app/views/layouts/_header_contents.html.haml
.header_contents
  .top_header
    .top_header__logo
      = image_tag 'logo.png'
    .top_header__contents
      %p
        映画好きな人たちが
      %p
        繋がるためのサイトを作りました。  
      %p
        １．友達申請機能
      %p
        ２．マイムービーランキング機能
      %p
        ３．映画レビュー機能
      %p
        ４．メッセージ機能

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MovieRoom
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header.header
      .header__title
        = link_to root_path, class: "header__title--text" do
          = image_tag 'logo.png'
          Movie Room
      .header__right
        - if user_signed_in?
          = link_to movies_search_path, class: "header__right--btn" do
            映画を探す
            = icon('fa', 'search')
          = link_to user_path(current_user), class: "header__right--btn" do
            = current_user.name
            = icon('fa', 'user-circle')
          = link_to destroy_user_session_path, method: :delete, class: "header__right--btn" do
            ログアウト
            = icon('fa', 'sign-out-alt')
        - else
          -# - if devise_mapping.registerable? && controller_name != 'registrations'
          = link_to new_registration_path(resource_name), class: 'header__right--btn' do
            ユーザー登録
            = icon('fa', 'user-plus')
          = link_to new_user_session_path, class: "header__right--btn" do
            ログイン
            = icon('fa', 'sign-in-alt')


    - if request.path == new_user_session_path 
      = render 'layouts/notifications'
      = yield
      = render 'layouts/footer'
    - elsif request.path == '/' 
      = render 'layouts/notifications'
      = render 'layouts/header_contents'
      = yield
      = render 'layouts/footer'
    - else
      .contents
        = render 'layouts/notifications'
        = yield
        = render 'layouts/footer'